//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.26 at 11:00:54 PM ICT 
//


package un.unece.uncefact.codelist.standard.unece.deliverytermscode._2010;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryTermsCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="DeliveryTermsCodeContentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="1"/&gt;
 *     &lt;enumeration value="2"/&gt;
 *     &lt;enumeration value="CFR"/&gt;
 *     &lt;enumeration value="CIF"/&gt;
 *     &lt;enumeration value="CIP"/&gt;
 *     &lt;enumeration value="CPT"/&gt;
 *     &lt;enumeration value="DAP"/&gt;
 *     &lt;enumeration value="DAT"/&gt;
 *     &lt;enumeration value="DDP"/&gt;
 *     &lt;enumeration value="EXW"/&gt;
 *     &lt;enumeration value="FAS"/&gt;
 *     &lt;enumeration value="FCA"/&gt;
 *     &lt;enumeration value="FOB"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DeliveryTermsCodeContentType", namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010")
@XmlEnum
public enum DeliveryTermsCodeContentType {


    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Delivery arranged by the supplier&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Indicates that the supplier will arrange delivery of the goods.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("1")
    VALUE_1("1"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Delivery arranged by logistic service provider&lt;/ccts:Name&gt;
     * </pre>
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Description xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Code indicating that the logistic service provider has arranged the delivery of goods.&lt;/ccts:Description&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("2")
    VALUE_2("2"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Cost and Freight (insert named port of destination)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("CFR")
    VALUE_3("CFR"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Cost, Insurance and Freight (insert named port of destination)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("CIF")
    VALUE_4("CIF"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Carriage and Insurance Paid to (insert named place of destination)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("CIP")
    VALUE_5("CIP"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Carriage Paid To (insert named place of destination)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("CPT")
    VALUE_6("CPT"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Delivered At Place (insert named place of destination)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("DAP")
    VALUE_7("DAP"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Delivered At Terminal (insert named terminal at port or place of destination)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("DAT")
    VALUE_8("DAT"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Delivered Duty Paid (insert named place of destination)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("DDP")
    VALUE_9("DDP"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Ex Works (insert named place of delivery)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("EXW")
    VALUE_10("EXW"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Free Alongside Ship (insert named port of shipment)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("FAS")
    VALUE_11("FAS"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Free Carrier (insert named place of delivery)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("FCA")
    VALUE_12("FCA"),

    /**
     * 
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Name xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm64053="urn:un:unece:uncefact:codelist:standard:UNECE:DeliveryTermsCode:2010" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Free On Board (insert named port of shipment)&lt;/ccts:Name&gt;
     * </pre>
     * 
     * 
     */
    @XmlEnumValue("FOB")
    VALUE_13("FOB");
    private final String value;

    DeliveryTermsCodeContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeliveryTermsCodeContentType fromValue(String v) {
        for (DeliveryTermsCodeContentType c: DeliveryTermsCodeContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
