//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.26 at 11:00:54 PM ICT 
//


package etda.uncefact.data.standard.invoice_reusableaggregatebusinessinformationentity._2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UN01005988&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Acronym xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ABIE&lt;/ccts:Acronym&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;CIIL_ Supply Chain_ Trade Line Item. Details&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Version xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:Version&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A collection of Cross Industry Invoice Line (CIIL) information specific to an item being used or reported on for supply chain trade purposes.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:ObjectClassTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Trade Line Item&lt;/ccts:ObjectClassTerm&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;CIIL&lt;/ccts:ObjectClassQualifierTerm&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:ObjectClassQualifierTerm xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Supply Chain&lt;/ccts:ObjectClassQualifierTerm&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:BusinessProcessContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Invoicing&lt;/ccts:BusinessProcessContextValue&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:GeopoliticalOrRegionContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;In All Contexts&lt;/ccts:GeopoliticalOrRegionContextValue&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:OfficialConstraintContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;None&lt;/ccts:OfficialConstraintContextValue&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:ProductContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;In All Contexts&lt;/ccts:ProductContextValue&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:IndustryContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Cross Industry&lt;/ccts:IndustryContextValue&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:BusinessProcessRoleContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;In All Contexts&lt;/ccts:BusinessProcessRoleContextValue&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:SupportingRoleContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;In All Contexts&lt;/ccts:SupportingRoleContextValue&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:SystemCapabilitiesContextValue xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:qdt="urn:etda:uncefact:data:standard:Invoice_QualifiedDataType:1" xmlns:ram="urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;In All Contexts&lt;/ccts:SystemCapabilitiesContextValue&gt;
 * </pre>
 * 
 * 
 * <p>Java class for CIILSupplyChainTradeLineItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIILSupplyChainTradeLineItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AssociatedCIILDocumentLineDocument" type="{urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2}CIILDocumentLineDocumentType"/&gt;
 *         &lt;element name="SpecifiedCIILSupplyChainTradeAgreement" type="{urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2}CIILSupplyChainTradeAgreementType" minOccurs="0"/&gt;
 *         &lt;element name="SpecifiedCIILSupplyChainTradeDelivery" type="{urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2}CIILSupplyChainTradeDeliveryType" minOccurs="0"/&gt;
 *         &lt;element name="SpecifiedCIILSupplyChainTradeSettlement" type="{urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2}CIILSupplyChainTradeSettlementType"/&gt;
 *         &lt;element name="SpecifiedCITradeProduct" type="{urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:2}CITradeProductType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIILSupplyChainTradeLineItemType", propOrder = {
    "associatedCIILDocumentLineDocument",
    "specifiedCIILSupplyChainTradeAgreement",
    "specifiedCIILSupplyChainTradeDelivery",
    "specifiedCIILSupplyChainTradeSettlement",
    "specifiedCITradeProduct"
})
public class CIILSupplyChainTradeLineItemType {

    @XmlElement(name = "AssociatedCIILDocumentLineDocument", required = true)
    protected CIILDocumentLineDocumentType associatedCIILDocumentLineDocument;
    @XmlElement(name = "SpecifiedCIILSupplyChainTradeAgreement")
    protected CIILSupplyChainTradeAgreementType specifiedCIILSupplyChainTradeAgreement;
    @XmlElement(name = "SpecifiedCIILSupplyChainTradeDelivery")
    protected CIILSupplyChainTradeDeliveryType specifiedCIILSupplyChainTradeDelivery;
    @XmlElement(name = "SpecifiedCIILSupplyChainTradeSettlement", required = true)
    protected CIILSupplyChainTradeSettlementType specifiedCIILSupplyChainTradeSettlement;
    @XmlElement(name = "SpecifiedCITradeProduct", required = true)
    protected CITradeProductType specifiedCITradeProduct;

    /**
     * Gets the value of the associatedCIILDocumentLineDocument property.
     * 
     * @return
     *     possible object is
     *     {@link CIILDocumentLineDocumentType }
     *     
     */
    public CIILDocumentLineDocumentType getAssociatedCIILDocumentLineDocument() {
        return associatedCIILDocumentLineDocument;
    }

    /**
     * Sets the value of the associatedCIILDocumentLineDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIILDocumentLineDocumentType }
     *     
     */
    public void setAssociatedCIILDocumentLineDocument(CIILDocumentLineDocumentType value) {
        this.associatedCIILDocumentLineDocument = value;
    }

    /**
     * Gets the value of the specifiedCIILSupplyChainTradeAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link CIILSupplyChainTradeAgreementType }
     *     
     */
    public CIILSupplyChainTradeAgreementType getSpecifiedCIILSupplyChainTradeAgreement() {
        return specifiedCIILSupplyChainTradeAgreement;
    }

    /**
     * Sets the value of the specifiedCIILSupplyChainTradeAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIILSupplyChainTradeAgreementType }
     *     
     */
    public void setSpecifiedCIILSupplyChainTradeAgreement(CIILSupplyChainTradeAgreementType value) {
        this.specifiedCIILSupplyChainTradeAgreement = value;
    }

    /**
     * Gets the value of the specifiedCIILSupplyChainTradeDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link CIILSupplyChainTradeDeliveryType }
     *     
     */
    public CIILSupplyChainTradeDeliveryType getSpecifiedCIILSupplyChainTradeDelivery() {
        return specifiedCIILSupplyChainTradeDelivery;
    }

    /**
     * Sets the value of the specifiedCIILSupplyChainTradeDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIILSupplyChainTradeDeliveryType }
     *     
     */
    public void setSpecifiedCIILSupplyChainTradeDelivery(CIILSupplyChainTradeDeliveryType value) {
        this.specifiedCIILSupplyChainTradeDelivery = value;
    }

    /**
     * Gets the value of the specifiedCIILSupplyChainTradeSettlement property.
     * 
     * @return
     *     possible object is
     *     {@link CIILSupplyChainTradeSettlementType }
     *     
     */
    public CIILSupplyChainTradeSettlementType getSpecifiedCIILSupplyChainTradeSettlement() {
        return specifiedCIILSupplyChainTradeSettlement;
    }

    /**
     * Sets the value of the specifiedCIILSupplyChainTradeSettlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIILSupplyChainTradeSettlementType }
     *     
     */
    public void setSpecifiedCIILSupplyChainTradeSettlement(CIILSupplyChainTradeSettlementType value) {
        this.specifiedCIILSupplyChainTradeSettlement = value;
    }

    /**
     * Gets the value of the specifiedCITradeProduct property.
     * 
     * @return
     *     possible object is
     *     {@link CITradeProductType }
     *     
     */
    public CITradeProductType getSpecifiedCITradeProduct() {
        return specifiedCITradeProduct;
    }

    /**
     * Sets the value of the specifiedCITradeProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link CITradeProductType }
     *     
     */
    public void setSpecifiedCITradeProduct(CITradeProductType value) {
        this.specifiedCITradeProduct = value;
    }

}
