//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.12 at 05:38:41 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:un:unece:uncefact:data:standard:UnqualifiedDataType:16", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package un.unece.uncefact.data.standard.unqualifieddatatype._16;
