//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.12 at 05:38:41 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:etda:uncefact:data:standard:TaxInvoice_ReusableAggregateBusinessInformationEntity:2", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package etda.uncefact.data.standard.taxinvoice_reusableaggregatebusinessinformationentity._2;
