//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.26 at 11:00:54 PM ICT 
//


package etda.uncefact.data.standard.invoice_reusableaggregatebusinessinformationentity._1;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the etda.uncefact.data.standard.invoice_reusableaggregatebusinessinformationentity._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CIExchangedDocumentContext_QNAME = new QName("urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", "CIExchangedDocumentContext");
    private final static QName _CIDocumentContextParameter_QNAME = new QName("urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", "CIDocumentContextParameter");
    private final static QName _CIIHExchangedDocument_QNAME = new QName("urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", "CIIHExchangedDocument");
    private final static QName _CIIHSupplyChainTradeTransaction_QNAME = new QName("urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", "CIIHSupplyChainTradeTransaction");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: etda.uncefact.data.standard.invoice_reusableaggregatebusinessinformationentity._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CIExchangedDocumentContextType }
     * 
     */
    public CIExchangedDocumentContextType createCIExchangedDocumentContextType() {
        return new CIExchangedDocumentContextType();
    }

    /**
     * Create an instance of {@link CIDocumentContextParameterType }
     * 
     */
    public CIDocumentContextParameterType createCIDocumentContextParameterType() {
        return new CIDocumentContextParameterType();
    }

    /**
     * Create an instance of {@link CIIHExchangedDocumentType }
     * 
     */
    public CIIHExchangedDocumentType createCIIHExchangedDocumentType() {
        return new CIIHExchangedDocumentType();
    }

    /**
     * Create an instance of {@link CIIHSupplyChainTradeTransactionType }
     * 
     */
    public CIIHSupplyChainTradeTransactionType createCIIHSupplyChainTradeTransactionType() {
        return new CIIHSupplyChainTradeTransactionType();
    }

    /**
     * Create an instance of {@link CINoteType }
     * 
     */
    public CINoteType createCINoteType() {
        return new CINoteType();
    }

    /**
     * Create an instance of {@link CIIHSupplyChainTradeAgreementType }
     * 
     */
    public CIIHSupplyChainTradeAgreementType createCIIHSupplyChainTradeAgreementType() {
        return new CIIHSupplyChainTradeAgreementType();
    }

    /**
     * Create an instance of {@link CIIHSupplyChainTradeDeliveryType }
     * 
     */
    public CIIHSupplyChainTradeDeliveryType createCIIHSupplyChainTradeDeliveryType() {
        return new CIIHSupplyChainTradeDeliveryType();
    }

    /**
     * Create an instance of {@link CIIHSupplyChainTradeSettlementType }
     * 
     */
    public CIIHSupplyChainTradeSettlementType createCIIHSupplyChainTradeSettlementType() {
        return new CIIHSupplyChainTradeSettlementType();
    }

    /**
     * Create an instance of {@link CIILSupplyChainTradeLineItemType }
     * 
     */
    public CIILSupplyChainTradeLineItemType createCIILSupplyChainTradeLineItemType() {
        return new CIILSupplyChainTradeLineItemType();
    }

    /**
     * Create an instance of {@link CITradePartyType }
     * 
     */
    public CITradePartyType createCITradePartyType() {
        return new CITradePartyType();
    }

    /**
     * Create an instance of {@link CILegalOrganizationType }
     * 
     */
    public CILegalOrganizationType createCILegalOrganizationType() {
        return new CILegalOrganizationType();
    }

    /**
     * Create an instance of {@link CITradeContactType }
     * 
     */
    public CITradeContactType createCITradeContactType() {
        return new CITradeContactType();
    }

    /**
     * Create an instance of {@link CIUniversalCommunicationType }
     * 
     */
    public CIUniversalCommunicationType createCIUniversalCommunicationType() {
        return new CIUniversalCommunicationType();
    }

    /**
     * Create an instance of {@link CITradeAddressType }
     * 
     */
    public CITradeAddressType createCITradeAddressType() {
        return new CITradeAddressType();
    }

    /**
     * Create an instance of {@link CITradeDeliveryTermsType }
     * 
     */
    public CITradeDeliveryTermsType createCITradeDeliveryTermsType() {
        return new CITradeDeliveryTermsType();
    }

    /**
     * Create an instance of {@link CIReferencedDocumentType }
     * 
     */
    public CIReferencedDocumentType createCIReferencedDocumentType() {
        return new CIReferencedDocumentType();
    }

    /**
     * Create an instance of {@link CISupplyChainEventType }
     * 
     */
    public CISupplyChainEventType createCISupplyChainEventType() {
        return new CISupplyChainEventType();
    }

    /**
     * Create an instance of {@link CITradeTaxType }
     * 
     */
    public CITradeTaxType createCITradeTaxType() {
        return new CITradeTaxType();
    }

    /**
     * Create an instance of {@link CITradeAllowanceChargeType }
     * 
     */
    public CITradeAllowanceChargeType createCITradeAllowanceChargeType() {
        return new CITradeAllowanceChargeType();
    }

    /**
     * Create an instance of {@link CITradePaymentTermsType }
     * 
     */
    public CITradePaymentTermsType createCITradePaymentTermsType() {
        return new CITradePaymentTermsType();
    }

    /**
     * Create an instance of {@link CIIHTradeSettlementMonetarySummationType }
     * 
     */
    public CIIHTradeSettlementMonetarySummationType createCIIHTradeSettlementMonetarySummationType() {
        return new CIIHTradeSettlementMonetarySummationType();
    }

    /**
     * Create an instance of {@link CIILDocumentLineDocumentType }
     * 
     */
    public CIILDocumentLineDocumentType createCIILDocumentLineDocumentType() {
        return new CIILDocumentLineDocumentType();
    }

    /**
     * Create an instance of {@link CIILSupplyChainTradeAgreementType }
     * 
     */
    public CIILSupplyChainTradeAgreementType createCIILSupplyChainTradeAgreementType() {
        return new CIILSupplyChainTradeAgreementType();
    }

    /**
     * Create an instance of {@link CITradePriceType }
     * 
     */
    public CITradePriceType createCITradePriceType() {
        return new CITradePriceType();
    }

    /**
     * Create an instance of {@link CIILSupplyChainTradeDeliveryType }
     * 
     */
    public CIILSupplyChainTradeDeliveryType createCIILSupplyChainTradeDeliveryType() {
        return new CIILSupplyChainTradeDeliveryType();
    }

    /**
     * Create an instance of {@link CIILSupplyChainTradeSettlementType }
     * 
     */
    public CIILSupplyChainTradeSettlementType createCIILSupplyChainTradeSettlementType() {
        return new CIILSupplyChainTradeSettlementType();
    }

    /**
     * Create an instance of {@link CIILTradeSettlementMonetarySummationType }
     * 
     */
    public CIILTradeSettlementMonetarySummationType createCIILTradeSettlementMonetarySummationType() {
        return new CIILTradeSettlementMonetarySummationType();
    }

    /**
     * Create an instance of {@link CITradeProductType }
     * 
     */
    public CITradeProductType createCITradeProductType() {
        return new CITradeProductType();
    }

    /**
     * Create an instance of {@link CITradeProductInstanceType }
     * 
     */
    public CITradeProductInstanceType createCITradeProductInstanceType() {
        return new CITradeProductInstanceType();
    }

    /**
     * Create an instance of {@link CITradeCountryType }
     * 
     */
    public CITradeCountryType createCITradeCountryType() {
        return new CITradeCountryType();
    }

    /**
     * Create an instance of {@link TelephoneCIUniversalCommunicationType }
     * 
     */
    public TelephoneCIUniversalCommunicationType createTelephoneCIUniversalCommunicationType() {
        return new TelephoneCIUniversalCommunicationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIExchangedDocumentContextType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIExchangedDocumentContextType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", name = "CIExchangedDocumentContext")
    public JAXBElement<CIExchangedDocumentContextType> createCIExchangedDocumentContext(CIExchangedDocumentContextType value) {
        return new JAXBElement<CIExchangedDocumentContextType>(_CIExchangedDocumentContext_QNAME, CIExchangedDocumentContextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIDocumentContextParameterType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIDocumentContextParameterType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", name = "CIDocumentContextParameter")
    public JAXBElement<CIDocumentContextParameterType> createCIDocumentContextParameter(CIDocumentContextParameterType value) {
        return new JAXBElement<CIDocumentContextParameterType>(_CIDocumentContextParameter_QNAME, CIDocumentContextParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIIHExchangedDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIIHExchangedDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", name = "CIIHExchangedDocument")
    public JAXBElement<CIIHExchangedDocumentType> createCIIHExchangedDocument(CIIHExchangedDocumentType value) {
        return new JAXBElement<CIIHExchangedDocumentType>(_CIIHExchangedDocument_QNAME, CIIHExchangedDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CIIHSupplyChainTradeTransactionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CIIHSupplyChainTradeTransactionType }{@code >}
     */
    @XmlElementDecl(namespace = "urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", name = "CIIHSupplyChainTradeTransaction")
    public JAXBElement<CIIHSupplyChainTradeTransactionType> createCIIHSupplyChainTradeTransaction(CIIHSupplyChainTradeTransactionType value) {
        return new JAXBElement<CIIHSupplyChainTradeTransactionType>(_CIIHSupplyChainTradeTransaction_QNAME, CIIHSupplyChainTradeTransactionType.class, null, value);
    }

}
