//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.26 at 11:00:54 PM ICT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:etda:uncefact:data:standard:Invoice_ReusableAggregateBusinessInformationEntity:1", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package etda.uncefact.data.standard.invoice_reusableaggregatebusinessinformationentity._1;
