//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.12 at 05:38:41 PM ICT 
//


package un.unece.uncefact.codelist.standard.unece.allowancechargereasoncode.d15b;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllowanceChargeReasonCodeContentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="AllowanceChargeReasonCodeContentType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="1"/&gt;
 *     &lt;enumeration value="2"/&gt;
 *     &lt;enumeration value="3"/&gt;
 *     &lt;enumeration value="4"/&gt;
 *     &lt;enumeration value="5"/&gt;
 *     &lt;enumeration value="6"/&gt;
 *     &lt;enumeration value="7"/&gt;
 *     &lt;enumeration value="8"/&gt;
 *     &lt;enumeration value="9"/&gt;
 *     &lt;enumeration value="10"/&gt;
 *     &lt;enumeration value="11"/&gt;
 *     &lt;enumeration value="12"/&gt;
 *     &lt;enumeration value="13"/&gt;
 *     &lt;enumeration value="14"/&gt;
 *     &lt;enumeration value="15"/&gt;
 *     &lt;enumeration value="16"/&gt;
 *     &lt;enumeration value="17"/&gt;
 *     &lt;enumeration value="18"/&gt;
 *     &lt;enumeration value="19"/&gt;
 *     &lt;enumeration value="20"/&gt;
 *     &lt;enumeration value="21"/&gt;
 *     &lt;enumeration value="22"/&gt;
 *     &lt;enumeration value="23"/&gt;
 *     &lt;enumeration value="24"/&gt;
 *     &lt;enumeration value="25"/&gt;
 *     &lt;enumeration value="26"/&gt;
 *     &lt;enumeration value="27"/&gt;
 *     &lt;enumeration value="28"/&gt;
 *     &lt;enumeration value="29"/&gt;
 *     &lt;enumeration value="30"/&gt;
 *     &lt;enumeration value="31"/&gt;
 *     &lt;enumeration value="32"/&gt;
 *     &lt;enumeration value="33"/&gt;
 *     &lt;enumeration value="34"/&gt;
 *     &lt;enumeration value="35"/&gt;
 *     &lt;enumeration value="36"/&gt;
 *     &lt;enumeration value="37"/&gt;
 *     &lt;enumeration value="38"/&gt;
 *     &lt;enumeration value="39"/&gt;
 *     &lt;enumeration value="40"/&gt;
 *     &lt;enumeration value="41"/&gt;
 *     &lt;enumeration value="42"/&gt;
 *     &lt;enumeration value="43"/&gt;
 *     &lt;enumeration value="44"/&gt;
 *     &lt;enumeration value="45"/&gt;
 *     &lt;enumeration value="46"/&gt;
 *     &lt;enumeration value="47"/&gt;
 *     &lt;enumeration value="48"/&gt;
 *     &lt;enumeration value="49"/&gt;
 *     &lt;enumeration value="50"/&gt;
 *     &lt;enumeration value="51"/&gt;
 *     &lt;enumeration value="52"/&gt;
 *     &lt;enumeration value="53"/&gt;
 *     &lt;enumeration value="54"/&gt;
 *     &lt;enumeration value="55"/&gt;
 *     &lt;enumeration value="56"/&gt;
 *     &lt;enumeration value="57"/&gt;
 *     &lt;enumeration value="58"/&gt;
 *     &lt;enumeration value="59"/&gt;
 *     &lt;enumeration value="60"/&gt;
 *     &lt;enumeration value="61"/&gt;
 *     &lt;enumeration value="62"/&gt;
 *     &lt;enumeration value="63"/&gt;
 *     &lt;enumeration value="64"/&gt;
 *     &lt;enumeration value="65"/&gt;
 *     &lt;enumeration value="66"/&gt;
 *     &lt;enumeration value="67"/&gt;
 *     &lt;enumeration value="68"/&gt;
 *     &lt;enumeration value="69"/&gt;
 *     &lt;enumeration value="70"/&gt;
 *     &lt;enumeration value="71"/&gt;
 *     &lt;enumeration value="72"/&gt;
 *     &lt;enumeration value="73"/&gt;
 *     &lt;enumeration value="74"/&gt;
 *     &lt;enumeration value="75"/&gt;
 *     &lt;enumeration value="76"/&gt;
 *     &lt;enumeration value="77"/&gt;
 *     &lt;enumeration value="78"/&gt;
 *     &lt;enumeration value="79"/&gt;
 *     &lt;enumeration value="80"/&gt;
 *     &lt;enumeration value="81"/&gt;
 *     &lt;enumeration value="82"/&gt;
 *     &lt;enumeration value="83"/&gt;
 *     &lt;enumeration value="84"/&gt;
 *     &lt;enumeration value="85"/&gt;
 *     &lt;enumeration value="86"/&gt;
 *     &lt;enumeration value="87"/&gt;
 *     &lt;enumeration value="88"/&gt;
 *     &lt;enumeration value="89"/&gt;
 *     &lt;enumeration value="90"/&gt;
 *     &lt;enumeration value="91"/&gt;
 *     &lt;enumeration value="92"/&gt;
 *     &lt;enumeration value="93"/&gt;
 *     &lt;enumeration value="94"/&gt;
 *     &lt;enumeration value="95"/&gt;
 *     &lt;enumeration value="96"/&gt;
 *     &lt;enumeration value="97"/&gt;
 *     &lt;enumeration value="ZZZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AllowanceChargeReasonCodeContentType", namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:AllowanceChargeReasonCode:D15B")
@XmlEnum
public enum AllowanceChargeReasonCodeContentType {

    @XmlEnumValue("1")
    VALUE_1("1"),
    @XmlEnumValue("2")
    VALUE_2("2"),
    @XmlEnumValue("3")
    VALUE_3("3"),
    @XmlEnumValue("4")
    VALUE_4("4"),
    @XmlEnumValue("5")
    VALUE_5("5"),
    @XmlEnumValue("6")
    VALUE_6("6"),
    @XmlEnumValue("7")
    VALUE_7("7"),
    @XmlEnumValue("8")
    VALUE_8("8"),
    @XmlEnumValue("9")
    VALUE_9("9"),
    @XmlEnumValue("10")
    VALUE_10("10"),
    @XmlEnumValue("11")
    VALUE_11("11"),
    @XmlEnumValue("12")
    VALUE_12("12"),
    @XmlEnumValue("13")
    VALUE_13("13"),
    @XmlEnumValue("14")
    VALUE_14("14"),
    @XmlEnumValue("15")
    VALUE_15("15"),
    @XmlEnumValue("16")
    VALUE_16("16"),
    @XmlEnumValue("17")
    VALUE_17("17"),
    @XmlEnumValue("18")
    VALUE_18("18"),
    @XmlEnumValue("19")
    VALUE_19("19"),
    @XmlEnumValue("20")
    VALUE_20("20"),
    @XmlEnumValue("21")
    VALUE_21("21"),
    @XmlEnumValue("22")
    VALUE_22("22"),
    @XmlEnumValue("23")
    VALUE_23("23"),
    @XmlEnumValue("24")
    VALUE_24("24"),
    @XmlEnumValue("25")
    VALUE_25("25"),
    @XmlEnumValue("26")
    VALUE_26("26"),
    @XmlEnumValue("27")
    VALUE_27("27"),
    @XmlEnumValue("28")
    VALUE_28("28"),
    @XmlEnumValue("29")
    VALUE_29("29"),
    @XmlEnumValue("30")
    VALUE_30("30"),
    @XmlEnumValue("31")
    VALUE_31("31"),
    @XmlEnumValue("32")
    VALUE_32("32"),
    @XmlEnumValue("33")
    VALUE_33("33"),
    @XmlEnumValue("34")
    VALUE_34("34"),
    @XmlEnumValue("35")
    VALUE_35("35"),
    @XmlEnumValue("36")
    VALUE_36("36"),
    @XmlEnumValue("37")
    VALUE_37("37"),
    @XmlEnumValue("38")
    VALUE_38("38"),
    @XmlEnumValue("39")
    VALUE_39("39"),
    @XmlEnumValue("40")
    VALUE_40("40"),
    @XmlEnumValue("41")
    VALUE_41("41"),
    @XmlEnumValue("42")
    VALUE_42("42"),
    @XmlEnumValue("43")
    VALUE_43("43"),
    @XmlEnumValue("44")
    VALUE_44("44"),
    @XmlEnumValue("45")
    VALUE_45("45"),
    @XmlEnumValue("46")
    VALUE_46("46"),
    @XmlEnumValue("47")
    VALUE_47("47"),
    @XmlEnumValue("48")
    VALUE_48("48"),
    @XmlEnumValue("49")
    VALUE_49("49"),
    @XmlEnumValue("50")
    VALUE_50("50"),
    @XmlEnumValue("51")
    VALUE_51("51"),
    @XmlEnumValue("52")
    VALUE_52("52"),
    @XmlEnumValue("53")
    VALUE_53("53"),
    @XmlEnumValue("54")
    VALUE_54("54"),
    @XmlEnumValue("55")
    VALUE_55("55"),
    @XmlEnumValue("56")
    VALUE_56("56"),
    @XmlEnumValue("57")
    VALUE_57("57"),
    @XmlEnumValue("58")
    VALUE_58("58"),
    @XmlEnumValue("59")
    VALUE_59("59"),
    @XmlEnumValue("60")
    VALUE_60("60"),
    @XmlEnumValue("61")
    VALUE_61("61"),
    @XmlEnumValue("62")
    VALUE_62("62"),
    @XmlEnumValue("63")
    VALUE_63("63"),
    @XmlEnumValue("64")
    VALUE_64("64"),
    @XmlEnumValue("65")
    VALUE_65("65"),
    @XmlEnumValue("66")
    VALUE_66("66"),
    @XmlEnumValue("67")
    VALUE_67("67"),
    @XmlEnumValue("68")
    VALUE_68("68"),
    @XmlEnumValue("69")
    VALUE_69("69"),
    @XmlEnumValue("70")
    VALUE_70("70"),
    @XmlEnumValue("71")
    VALUE_71("71"),
    @XmlEnumValue("72")
    VALUE_72("72"),
    @XmlEnumValue("73")
    VALUE_73("73"),
    @XmlEnumValue("74")
    VALUE_74("74"),
    @XmlEnumValue("75")
    VALUE_75("75"),
    @XmlEnumValue("76")
    VALUE_76("76"),
    @XmlEnumValue("77")
    VALUE_77("77"),
    @XmlEnumValue("78")
    VALUE_78("78"),
    @XmlEnumValue("79")
    VALUE_79("79"),
    @XmlEnumValue("80")
    VALUE_80("80"),
    @XmlEnumValue("81")
    VALUE_81("81"),
    @XmlEnumValue("82")
    VALUE_82("82"),
    @XmlEnumValue("83")
    VALUE_83("83"),
    @XmlEnumValue("84")
    VALUE_84("84"),
    @XmlEnumValue("85")
    VALUE_85("85"),
    @XmlEnumValue("86")
    VALUE_86("86"),
    @XmlEnumValue("87")
    VALUE_87("87"),
    @XmlEnumValue("88")
    VALUE_88("88"),
    @XmlEnumValue("89")
    VALUE_89("89"),
    @XmlEnumValue("90")
    VALUE_90("90"),
    @XmlEnumValue("91")
    VALUE_91("91"),
    @XmlEnumValue("92")
    VALUE_92("92"),
    @XmlEnumValue("93")
    VALUE_93("93"),
    @XmlEnumValue("94")
    VALUE_94("94"),
    @XmlEnumValue("95")
    VALUE_95("95"),
    @XmlEnumValue("96")
    VALUE_96("96"),
    @XmlEnumValue("97")
    VALUE_97("97"),
    @XmlEnumValue("ZZZ")
    VALUE_98("ZZZ");
    private final String value;

    AllowanceChargeReasonCodeContentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AllowanceChargeReasonCodeContentType fromValue(String v) {
        for (AllowanceChargeReasonCodeContentType c: AllowanceChargeReasonCodeContentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
